# Generated by Django 5.0.3 on 2024-03-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('booking_id', models.IntegerField()),
                ('bus_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('no_of_seats', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Booking List',
            },
        ),
        migrations.AlterField(
            model_name='bus',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
