# Generated by Django 5.0.3 on 2024-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_remove_book_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_id',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
