# Generated by Django 5.0.3 on 2024-03-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_alter_book_booking_id_alter_bus_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_id',
            field=models.CharField(max_length=5),
        ),
    ]
